name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        run: |
          apt-get update
          apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
          rsync -av ./ /root/ros2_ws/src/ros2_speedtest_pkg/
          cd /root/ros2_ws/src/ros2_speedtest_pkg
          python3 -m pip install -r /root/ros2_ws/src/ros2_speedtest_pkg/requirements.txt
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/ros2_speedtest_pkg/
          cd /root/ros2_ws
          bash -xv ./src/ros2_speedtest_pkg/test/test.bash /root
